name: Build Dist
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install modules
        run: |
          npm install
      - name: Run build
        run: |
          npm run build
      - name: Commit build
        run: |
          git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Build Distribution via ${{ github.sha }}"
          git push
